#
#   _____      _       __     __              ______              
#  / ____|    | |      \ \   / /             |  ____|             
# | |     __ _| |_ __ __\ \_/ /__  _   _ _ __| |__ __ _ _ __  ___ 
# | |    / _` | | '_ ` _ \   / _ \| | | | '__|  __/ _` | '_ \/ __|
# | |___| (_| | | | | | | | | (_) | |_| | |  | | | (_| | | | \__ \
#  \_____\__,_|_|_| |_| |_|_|\___/ \__,_|_|  |_|  \__,_|_| |_|___/
                                                                 
# 


[idrac]
ip = ""	# IP or Hostname
user = "root" #iDRAC IPMI user.		
password = "calvin" #iDRAC password

[fans]
speed = "25" #must be indicated in percentage. Generate server error if less than 25%
